### ISSUE TITLE
About some problems abdout NTU60

### ISSUE THREAD

**Issue by yangtianjin** [hehefan/P4Transformer#8] opened 2021-12-16 09:19 UTC
Can you provide some code about ntu60, we have some problems when reproducing

**Comment by SheldongChen** [comment] 2021-12-25 09:43
I was also unable to reproduce the results of the paper on the NTU dataset using p4trans

**Comment by hehefan** [comment] 2021-12-27 06:12
Hi,

The NTU 60 code will be released to [PST-Transfomer](https://github.com/hehefan/PST-Transformer) after the work is published. Please kindly watch the repo. 

Best regards.

**Comment by SheldongChen** [comment] 2022-01-11 08:46
> Can you provide some code about ntu60, we have some problems when reproducing

Hi, have you reproduced the code about ntu60 successfully now?

**Comment by hehefan** [comment] 2022-04-04 13:56
Code released.

**Closed as completed** 2022-04-04 13:56 UTC
